config/routes.rb
SampleApp::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  root :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base


  attr_accessor :password
  attr_accessible :name, :lastname, :email, :password, :password_confirmation

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :presence => true,
                   :length => {:maximum => 50}
  validates :lastname, :presence => true,
                   :length => {:maximum => 50}
  validates :email, :presence => true,
                    :format => {:with => email_regex},
                    :uniqueness => {:case_sensitive => false}
  validates :password, :presence => true, :confirmation => true, :length => {:within => 6..40}

  before_save :encrypt_password

    def has_password?(submitted_password)
      encrypted_password == encrypt(submitted_password)
    end

    def self.authenticate(email, submitted_password)
      user = find_by_email(email)
      (user && user.has_password?(submitted_password)) ? user : nil
      return nil if user.nil?
      return user if user.has_password?(submitted_password)
    end

    def self.authenticate_with_salt(id, cookie_salt)
      user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
    end
  private

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)

    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")      #Not final implementation
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"

  end

  def contact
    @title = "Contact"
  end
  def about
    @title = "About"

  end

   def helo
    @title = "Help"

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign inn"
  end

  def destroy
     sign_out
    redirect_to root_path

  end

  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid emil/password comabination."
      @title = "Sign in"
       render 'new'
    else
      sign_in user
      redirect_to user

    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    @title = "Sign up"
  end

  def show
      @user = User.find(params[:id])
      @title = @user.name
  end

  def create
     @user = User.new(params[:user])
     if @user.save
       sign_in @user
       flash[:success] = "Welcome to the sample app"
       redirect_to @user

     else
       @title = "Sign up"
        render 'new'
     end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #Return titlte on a per-page basis.

  def title
    base_title  = "Sample_app"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end

  end

  def logo
    image_tag("logo.png", :alt => "Sample app", :class => "round")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    current_user = user
  end


  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  private
  def user_from_remember_token
    User.authenticate_with_salt(*remember_token)
  end

  def remember_token
    cookies.signed[:remember_token] || [nil, nil]
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = {:size => 50})
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %> </li>

      <li><%= link_to "Contact", contact_path %> </li>

      <li><%= link_to "something", '#' %> </li>
      <li><%= link_to "About", 'http://www.vg.no' %> </li>

    </ul>

  </nav>

</footer>

app/views/layouts/_header.html.erb
<head>

  <title>
      <%= title %>
  </title>
    <%= csrf_meta_tag %>
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
     <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
  <%= stylesheet_link_tag 'costum', :media => 'screen' %>



</head>

app/views/layouts/application.html.erb
<!DOCTYPE html>
 <html>
<%= render 'layouts/header' %>

 <body>
    <div class="container">
      <header>
        <%= link_to logo, root_path%>
        <nav class="round">
          <ul>
            <li><%= link_to "Home", root_path %></li>



            <% if signed_in? %>
                <li><%= link_to "Profil", current_user %></li>
            <% end %>


            <li><%= link_to "Help", help_path %></li>

            <% if signed_in? %>
                <li><%= link_to "Sign out", signout_path %></li>

            <% else %>

                <li><%= link_to "Sign inn", signin_path %></li>
            <% end %>



          </ul>
        </nav>
      </header>
      <section class="round">
        <% flash.each do |key, value| %>
            <div class="flash <%= key  %>"><%= value %></div>
        <% end %>
         <%= yield %>
      </section>
            <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development?%>
    </div>
</body>
 </html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>This is about page</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>This is contact page</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>This is about help</p>

app/views/pages/home.html.erb
<h1>Home</h1>
<p>This is about home</p>

<%= link_to 'Sign up now', signup_path, :class => "signup_button round" %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>

    <div id="error_explanation">
      <h2>
          <%= pluralize(@user.errors.count, "error") %>
        prohibited this user from being saved
      </h2>

      <p>
        There were problems with the following fields
      </p>
      <ul>
          <%  @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      </ul>
        <% end %>
    </div>

<% end %>

app/views/users/new.html.erb
<h1>Registrer deg</h1>

<%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
    <div class="field">
        <%= f.label :name, "Fornavn" %><br/>
        <%= f.text_field :name %>
    </div>
    <div class="field">
        <%= f.label :lastname, "Etternavn" %><br/>
        <%= f.text_field :lastname %>
    </div>

    <div class="field">
        <%= f.label :email, "E-post" %><br/>
        <%= f.text_field :email %>
    </div>

    <div class="field">
        <%= f.label :password, "Passord" %><br/>
        <%= f.password_field :password %>
    </div>

    <div class="field">
        <%= f.label :password_confirmation, "Bekreft passord" %><br/>
        <%= f.password_field :password_confirmation %>
    </div>

    <div class="actions">
        <%= f.submit "Sign up" %>
    </div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
         <h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
  <%= @user.lastname %>
    </h1>
    </td>
        <td class="sidebar round">
          <strong>Name</strong>  <%= @user.name %><br/>
            <strong>URL</strong> <%= link_to user_path(@user),user_path(@user)  %>

        </td>
  </tr>

</table>